image: Ubuntu

stack: jdk 11
branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-order.jar -port=5555 &
  -
build_script:
  - chmod +x gradlew
  - - ./gradlew test --info
